### ISSUE TITLE
can't create dapp

### ISSUE THREAD

**Issue by bassjobsen** [AschPlatform/asch-cli#22]
running `asch-cli -H 127.0.0.1 -P 4096 registerdapp --metafile dapp.json --secret "nasty arm work trade sad orphan artist disorder trim cloth enable rescue"` will cause the following error:

```
buffer.js:481
    throw new TypeError('"string" must be a string, Buffer, or ArrayBuffer');
    ^

TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:481:11)
    at ByteBuffer.module.exports.ByteBufferPrototype.writeUTF8String (/home/bass/testomgeving/asch-cli/node_modules/asch-js/node_modules/bytebuffer/dist/bytebuffer-node.js:2004:20)
    at getBytes (/home/bass/testomgeving/asch-cli/node_modules/asch-js/lib/transactions/crypto.js:120:5)
    at getHash (/home/bass/testomgeving/asch-cli/node_modules/asch-js/lib/transactions/crypto.js:166:24)
    at Object.sign (/home/bass/testomgeving/asch-cli/node_modules/asch-js/lib/transactions/crypto.js:191:13)
    at Object.createDApp (/home/bass/testomgeving/asch-cli/node_modules/asch-js/lib/transactions/dapp.js:34:16)
    at Command.registerDapp (/home/bass/testomgeving/asch-cli/plugins/api.js:309:25)
    at Command.listener (/home/bass/testomgeving/asch-cli/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
```
The above seems due to https://github.com/AschPlatform/asch-js/issues/11

**Comment by bassjobsen** [comment]
fixed!
