### ISSUE TITLE
aschJS.transaction.createTransactionEx is not a function

### ISSUE THREAD

**Issue by bshy522** [AschPlatform/asch-cli#31]
```sh

> asch-cli -H 127.0.0.1 -P 4096 registerchain -e "maximum correct local collect moral theme silver mule tell gift reward only" -f chain.json
/Users/larry/code/asch-cli/plugins/api.js:312
  var trs = aschJS.transaction.createTransactionEx({
                               ^

TypeError: aschJS.transaction.createTransactionEx is not a function
    at Command.registerChain (/Users/larry/code/asch-cli/plugins/api.js:312:32)
    at Command.listener (/Users/larry/code/asch-cli/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/Users/larry/code/asch-cli/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/larry/code/asch-cli/node_modules/commander/index.js:474:21)
    at main (/Users/larry/code/asch-cli/index.js:26:13)
    at Object.<anonymous> (/Users/larry/code/asch-cli/index.js:29:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

**Comment by bshy522** [comment]
请问这是什么问题？

**Comment by bshy522** [comment]
1.4版本

**Comment by a1300** [comment]
@bshy522 `asch-cli` is currently not up to date. If you want to register your DApp you can use [asch-redeploy](https://github.com/AschPlatform/asch-redeploy)
